param(
  [string[]]$Tools = @('All'),
  [ValidateSet('Copy','Symlink')]
  [string]$Mode = 'Copy',
  [switch]$Force,
  [switch]$Validate,
  [switch]$ValidateAdapters,
  [string]$RootPath
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($RootPath)) {
  $RootPath = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
}

$root = (Resolve-Path -LiteralPath $RootPath).Path
$sourceSkills = Join-Path $root '.agents\skills'
$generatedMarker = 'Generated by scripts/setup-ai-tools.ps1. Source: .agents/skills.'
$validTools = @('All','Codex','Claude','Cursor','Copilot','None')

if (-not (Test-Path -LiteralPath $sourceSkills)) {
  throw "Canonical skills directory not found: $sourceSkills"
}

function Get-SelectedTools {
  param([string[]]$RequestedTools)

  $normalizedTools = @(
    foreach ($tool in $RequestedTools) {
      foreach ($part in ($tool -split ',')) {
        $trimmed = $part.Trim()
        if (-not [string]::IsNullOrWhiteSpace($trimmed)) {
          $trimmed
        }
      }
    }
  )

  foreach ($tool in $normalizedTools) {
    if ($validTools -notcontains $tool) {
      throw "Unsupported tool '$tool'. Valid tools: $($validTools -join ', ')."
    }
  }

  if (($normalizedTools -contains 'None') -and ($normalizedTools.Count -gt 1)) {
    throw "-Tools None cannot be combined with other tools."
  }

  if ($normalizedTools -contains 'None') {
    return @()
  }

  if ($normalizedTools -contains 'All') {
    return @('Codex','Claude','Cursor','Copilot')
  }

  return @($normalizedTools | Select-Object -Unique)
}

function Test-FileContains {
  param(
    [string]$Path,
    [string]$Needle
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    return $false
  }

  $text = Get-Content -Raw -LiteralPath $Path
  return $text.Contains($Needle)
}

function Set-GeneratedFile {
  param(
    [string]$Path,
    [string]$Content,
    [string]$Description
  )

  if (Test-Path -LiteralPath $Path) {
    if ($Force) {
      Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8
      Write-Host "  Replaced $Description because -Force was specified: $Path" -ForegroundColor Yellow
      return
    }

    Write-Host "  Validating existing ${Description}: $Path" -ForegroundColor Cyan
    if (-not (Test-FileContains -Path $Path -Needle $generatedMarker)) {
      Write-Warning "Existing $Description does not contain the setup generation marker. It was not overwritten. Use -Force only if replacing it is intentional."
    }
    return
  }

  $parent = Split-Path -Parent $Path
  if (-not [string]::IsNullOrWhiteSpace($parent)) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
  }

  Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8
  Write-Host "  Created ${Description}: $Path" -ForegroundColor Green
}

function Copy-SkillMirror {
  param(
    [string]$ToolName,
    [string]$DestinationRoot
  )

  Write-Host "Refreshing $ToolName skill mirror from .agents/skills: $DestinationRoot" -ForegroundColor Cyan
  New-Item -ItemType Directory -Force -Path $DestinationRoot | Out-Null

  $sourceDirectories = @(Get-ChildItem -LiteralPath $sourceSkills -Directory -Force)
  foreach ($sourceDirectory in $sourceDirectories) {
    $targetDirectory = Join-Path $DestinationRoot $sourceDirectory.Name

    if (Test-Path -LiteralPath $targetDirectory) {
      if (-not $Force) {
        Write-Warning "Skipping existing skill mirror '$targetDirectory'. Use -Force to replace it."
        continue
      }

      $resolvedTarget = (Resolve-Path -LiteralPath $targetDirectory).Path
      $resolvedDestinationRoot = (Resolve-Path -LiteralPath $DestinationRoot).Path
      if (-not $resolvedTarget.StartsWith($resolvedDestinationRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to remove path outside mirror root: $resolvedTarget"
      }

      Remove-Item -LiteralPath $targetDirectory -Recurse -Force
    }

    if ($Mode -eq 'Symlink') {
      New-Item -ItemType SymbolicLink -Path $targetDirectory -Target $sourceDirectory.FullName | Out-Null
      Write-Host "  Linked $($sourceDirectory.Name)" -ForegroundColor Green
    } else {
      Copy-Item -LiteralPath $sourceDirectory.FullName -Destination $targetDirectory -Recurse -Force
      Write-Host "  Copied $($sourceDirectory.Name)" -ForegroundColor Green
    }
  }
}

function Get-CodexReadmeContent {
  return @"
# Codex Adapter

<!-- $generatedMarker -->

Codex uses AGENTS.md, .agents/skills, .agents/workflows, and .codex/config.toml.

.agents/skills is the canonical source for repository skills. Do not create a separate Codex-only skills source.

.codex/config.toml contains conservative profiles and defaults only. Keep permissions restricted and require confirmation before destructive operations, dependency installation, worktree deletion, or MCP write-tool execution.
"@
}

function Get-CodexConfigContent {
  return @"
# $generatedMarker
# Codex should use .agents/skills as the canonical skill layer for this repository.
# Do not assume Codex reads .codex/agents/*.md; this file only defines conservative defaults and profiles.
# Keep permissions restricted. Do not enable destructive execution, broad filesystem access, or automatic network access by default.

model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[features]
multi_agent = true
"@
}

function Ensure-CodexAdapter {
  Write-Host 'Validating Codex static adapter.' -ForegroundColor Cyan
  Write-Host '  Codex reads .agents/skills directly; no Codex skill mirror is generated.' -ForegroundColor Cyan

  $codexRoot = Join-Path $root '.codex'
  New-Item -ItemType Directory -Force -Path $codexRoot | Out-Null

  Set-GeneratedFile `
    -Path (Join-Path $codexRoot 'README.md') `
    -Content (Get-CodexReadmeContent) `
    -Description 'Codex README'

  Set-GeneratedFile `
    -Path (Join-Path $codexRoot 'config.toml') `
    -Content (Get-CodexConfigContent) `
    -Description 'Codex config'
}

function Get-CopilotInstructionsContent {
  return @"
# GitHub Copilot instructions

<!-- $generatedMarker -->

Use AGENTS.md as the canonical source of repository rules.

Use .github/prompts/*.prompt.md for repeatable workflows.

Use docs/ai/ai-tooling-setup.md for AI tool setup and .agents/workflows for lifecycle, branch isolation, handoff, and validation rules.

For Revit API work:

- Keep Revit API calls inside src/RevitAiTemplate.Revit.
- Never call Revit API from WPF view models, WebView2 JavaScript handlers, MCP tools, AI Gateway, or tests.
- Use ExternalEvent for modeless UI, background, MCP, or bridge requests.
- Preserve the multi-version build strategy.
- Run ./scripts/check.ps1 when possible.
- Do not create arbitrary Revit API execution tools.
"@
}

function Get-CopilotPromptContent {
  param(
    [string]$Name,
    [string]$Description,
    [string]$Skill,
    [string]$Workflow
  )

  return @"
---
name: $Name
description: $Description
agent: agent
---

<!-- $generatedMarker -->

Use AGENTS.md and $Workflow as canonical guidance.

Use .agents/skills/$Skill/SKILL.md for the specialized role instructions.

Do not duplicate long skill content in this prompt.
"@
}

function Ensure-CopilotAdapter {
  Write-Host 'Validating GitHub Copilot static adapter.' -ForegroundColor Cyan
  Write-Host '  Copilot uses .github/copilot-instructions.md and .github/prompts; no skill mirror is generated.' -ForegroundColor Cyan

  $githubRoot = Join-Path $root '.github'
  $promptRoot = Join-Path $githubRoot 'prompts'
  New-Item -ItemType Directory -Force -Path $promptRoot | Out-Null

  Set-GeneratedFile `
    -Path (Join-Path $githubRoot 'copilot-instructions.md') `
    -Content (Get-CopilotInstructionsContent) `
    -Description 'Copilot instructions'

  $prompts = @(
    @{ Name = 'feature-plan'; Description = 'Plan a Revit AI template feature without implementing code.'; Skill = 'orchestrator-feature-lead'; Workflow = '.agents/workflows/feature-lifecycle.md' },
    @{ Name = 'product-requirements'; Description = 'Translate a product request into actionable Revit plugin requirements.'; Skill = 'requirements-analyst'; Workflow = '.agents/workflows/feature-lifecycle.md' },
    @{ Name = 'revit-api-review'; Description = 'Review Revit API usage, threading, ExternalEvent routing, and transactions.'; Skill = 'revit-api-senior'; Workflow = '.agents/workflows/validation-gates.md' },
    @{ Name = 'multiversion-impact'; Description = 'Review Revit 2024-2027 framework and API compatibility impact.'; Skill = 'revit-multiversion-architect'; Workflow = '.agents/workflows/validation-gates.md' },
    @{ Name = 'security-review'; Description = 'Review AI, MCP, secrets, privacy, and Revit write-operation security.'; Skill = 'cybersecurity-privacy-engineer'; Workflow = '.agents/workflows/validation-gates.md' },
    @{ Name = 'qa-validation'; Description = 'Create or run validation for Revit AI template changes.'; Skill = 'qa-automation-engineer'; Workflow = '.agents/workflows/validation-gates.md' },
    @{ Name = 'pr-summary'; Description = 'Prepare a concise PR summary grounded in the final diff and validation.'; Skill = 'pr-reviewer'; Workflow = '.agents/workflows/handoff-contract.md' },
    @{ Name = 'template-setup'; Description = 'Guide setup of AI tooling and template creation choices.'; Skill = 'visual-studio-template-engineer'; Workflow = '.agents/workflows/feature-lifecycle.md' }
  )

  foreach ($prompt in $prompts) {
    $promptPath = Join-Path $promptRoot "$($prompt.Name).prompt.md"
    $content = Get-CopilotPromptContent `
      -Name $prompt.Name `
      -Description $prompt.Description `
      -Skill $prompt.Skill `
      -Workflow $prompt.Workflow

    Set-GeneratedFile -Path $promptPath -Content $content -Description "Copilot prompt $($prompt.Name)"
  }
}

function Invoke-ScriptChecked {
  param(
    [scriptblock]$Command,
    [string]$Description
  )

  & $Command
  if ($LASTEXITCODE -ne 0) {
    throw "$Description failed with exit code $LASTEXITCODE."
  }
}

$selectedTools = Get-SelectedTools -RequestedTools $Tools

foreach ($tool in $selectedTools) {
  switch ($tool) {
    'Codex' {
      Ensure-CodexAdapter
    }
    'Claude' {
      Copy-SkillMirror -ToolName 'Claude' -DestinationRoot (Join-Path $root '.claude\skills')
    }
    'Cursor' {
      Copy-SkillMirror -ToolName 'Cursor' -DestinationRoot (Join-Path $root '.cursor\skills')
    }
    'Copilot' {
      Ensure-CopilotAdapter
    }
    default {
      throw "Unsupported tool: $tool"
    }
  }
}

if ($Validate) {
  $skillValidator = Join-Path $root 'scripts\validate-skills.ps1'
  if (-not (Test-Path -LiteralPath $skillValidator)) {
    throw "Skill validation script not found: $skillValidator"
  }

  Invoke-ScriptChecked `
    -Command { & $skillValidator -RootPath $root -IncludeMirrors } `
    -Description 'Skill validation'

  $ValidateAdapters = $true
}

if ($ValidateAdapters) {
  $adapterTools = $selectedTools
  if ($adapterTools.Count -eq 0) {
    $adapterTools = @('All')
  }

  $adapterValidator = Join-Path $root 'scripts\validate-ai-adapters.ps1'
  if (-not (Test-Path -LiteralPath $adapterValidator)) {
    throw "AI adapter parity validation script not found: $adapterValidator"
  }

  Invoke-ScriptChecked `
    -Command { & $adapterValidator -RootPath $root -Tools $adapterTools } `
    -Description 'AI adapter parity validation'
}

Write-Host 'AI tool setup completed.' -ForegroundColor Green
